In [1]:
l1=["sayali","abhi","sai","niku","a"]
for i in l1:
    j=len(i)
    print(j)
    for x in range(j):
        print("*",end=" ")
        print()
    print("-------------------------")
    if j<5:
        n=5
        for y in range(n):
            for z in range(y,n):
                print(" ",end=" ")
            for z in range(y):
                print("*",end=" ")
            for z in range(y+1):
                print("*",end=" ")
            print()
        print("///////////////////////////////")
    elif j>5:
        n=5
        for i in range(n):
            for j in range(n):
                print("*",end=" ")
            print()
        print("////////////////////////////////")

6
*
*
*
*
*
*
-------------------------
* * * * *
* * * * *
* * * * *
* * * * *
* * * * *
////////////////////////////////
4
*
*
*
*
-------------------------
          *
        * * *
      * * * * *
    * * * * * * *
  * * * * * * * * *
///////////////////////////////
3
*
*
*
-------------------------
          *
        * * *
      * * * * *
    * * * * * * *
  * * * * * * * * *
///////////////////////////////
4
*
*
*
*
-------------------------
          *
        * * *
      * * * * *
    * * * * * * *
  * * * * * * * * *
///////////////////////////////
1
*
-------------------------
          *
        * * *
      * * * * *
    * * * * * * *
  * * * * * * * * *
///////////////////////////////

In [3]:
colg=["JCJ","SIT","DKTE"]
marks=[]
def pro():
    for x in colg:
        if x=="JCJ":  
            for i in range(3):
                a=input("Enter the student name....")
                b=int(input("Enter the student mark...."))
                marks.append(b)
        elif x=="SIT":
            for y in range(5):
                c=input("Enter the student name....")
                d=int(input("Enter the student mark...."))
                marks.append(d)
        else:
            for z in range(7):
                e=input("Enter the student name....")
                f=int(input("Enter the student mark...."))
                marks.append(f)
    print(marks)
   
    if marks[5]%2==0:
        for o in range(6):
            for p in range(o+1):
                print("*",end=" ")
            print( )
    else:
        for l in range(6):
            for k in range(6):
                print("*",end=" ")
            print( )
pro()

Enter the student name....sayali
Enter the student mark....78
Enter the student name....kajal
Enter the student mark....88
Enter the student name....pooja
Enter the student mark....65
Enter the student name....nikita
Enter the student mark....45
Enter the student name....ankita
Enter the student mark....74
Enter the student name....nikita
Enter the student mark....52
Enter the student name....renu
Enter the student mark....63
Enter the student name....asfiya
Enter the student mark....44
Enter the student name....seema
Enter the student mark....85
Enter the student name....amar
Enter the student mark....82
Enter the student name....abhi
Enter the student mark....43
Enter the student name....sonali
Enter the student mark....50
Enter the student name....utkarsha
Enter the student mark....61
Enter the student name....sharau
Enter the student mark....55
Enter the student name....akshay
Enter the student mark....97
[78, 88, 65, 45, 74, 52, 63, 44, 85, 82, 43, 50, 61, 55, 97]
*
* *
* * *
* * * *
* * * * *
* * * * * *

In [1]:
ani=["Bald Eagles","Penguins","Cows","Elephants","Cat","Ducks","Kangaroos","Moose","Dogs","Lions",]
girls=["Nikita","Neha","Aaru","Shravni","Diksha"]
boys=["Dhiraj","Nikhil","Shiva","Darshan","Ajay"]
legs1=["Bald Eagles","Penguins","Ducks","Kangaroos"]
legs2=["Moose","Dogs","Lions","Cows","Elephants","Cat"]


for x in ani:
    for p in legs1:
        if x==p:
            boys.append(p)
print(boys)

for y in ani:
    for n in legs2:
        if y==n:
            girls.append(n)
print(girls)

ab=len(legs1)*2
print("Count of legs....",ab)

js=len(legs2)*4
print("Count of legs....",js)

['Dhiraj', 'Nikhil', 'Shiva', 'Darshan', 'Ajay', 'Bald Eagles', 'Penguins', 'Ducks', 'Kangaroos']
['Nikita', 'Neha', 'Aaru', 'Shravni', 'Diksha', 'Cows', 'Elephants', 'Cat', 'Moose', 'Dogs', 'Lions']
Count of legs.... 8
Count of legs.... 24